/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/connect/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connect/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cosmetics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CosmeticCatalogResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/ranked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RankedChallengeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedMatchSetResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matchsets/{setId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    setId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchSetResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    rules?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaderboardResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetaResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llms.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llms-full.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BotSummaryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBotRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedBot"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BotDetailResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}/appearance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBotAppearanceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdatedBotAppearance"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}/build-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BotBuildStatusResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}/versions/{versionId}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitVersionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmittedBotVersion"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BotMatchHistoryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BotStatistics"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MyBotResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChallengeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedMatchResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    take: number;
                    bot?: string;
                    map?: string;
                    ranked?: boolean;
                    skip?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchSummaryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{matchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    matchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchDetailResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{matchId}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    matchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchLiveResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{matchId}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    matchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    take?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserNotificationResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    notificationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BotActiveVersionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            versionNumber: number;
            artifactHash: null | string;
        };
        BotBuildStatusResponse: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            versionNumber: number;
            status: string;
            artifactHash: null | string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            builtAt: null | string;
        };
        BotCombatTotals: {
            /** Format: int32 */
            games: number;
            /** Format: int32 */
            damageDealt: number;
            /** Format: int32 */
            faults: number;
        };
        BotDetailResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            accent: string;
            lookId: string;
            projectileLookId: string;
            /** Format: date-time */
            createdAt: string;
            owner: string;
            isOwner: boolean;
            currentStanding: null | components["schemas"]["LadderStanding"];
            versions: components["schemas"]["BotVersionResponse"][];
        };
        BotLadderRatingResponse: {
            rulesVersion: string;
            /** Format: double */
            rating: number;
            /** Format: int32 */
            rankedSets: number;
        };
        BotMatchHistoryResponse: {
            /** Format: int32 */
            wins: number;
            /** Format: int32 */
            losses: number;
            /** Format: int32 */
            draws: number;
            matches: components["schemas"]["BotMatchHistoryRowResponse"][];
        };
        BotMatchHistoryRowResponse: {
            /** Format: uuid */
            id: string;
            mapId: string;
            status: string;
            broadcasting: boolean;
            /** Format: uuid */
            matchSetId: null | string;
            /** Format: int32 */
            setGame: null | number;
            /** Format: date-time */
            createdAt: string;
            outcome: null | string;
            opponent: null | components["schemas"]["BotMatchOpponentResponse"];
        };
        BotMatchOpponentResponse: {
            /** Format: uuid */
            botId: string;
            nameSnapshot: string;
            ownerDisplayNameSnapshot: string;
            accentSnapshot: string;
            lookIdSnapshot: string;
        };
        BotRecord: {
            /** Format: int32 */
            played: number;
            /** Format: int32 */
            wins: number;
            /** Format: int32 */
            losses: number;
            /** Format: int32 */
            draws: number;
        };
        BotStatistics: {
            overall: components["schemas"]["BotRecord"];
            ranked: components["schemas"]["BotRecord"];
            unranked: components["schemas"]["BotRecord"];
            combat: components["schemas"]["BotCombatTotals"];
        };
        BotSummaryResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            accent: string;
            lookId: string;
            projectileLookId: string;
            /** Format: date-time */
            createdAt: string;
            ratings: components["schemas"]["BotLadderRatingResponse"][];
            owner: string;
            activeVersion: null | components["schemas"]["BotActiveVersionResponse"];
            /** Format: int32 */
            versionCount: number;
            currentStanding?: null | components["schemas"]["LadderStanding"];
        };
        BotVersionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            versionNumber: number;
            status: string;
            artifactHash: null | string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            buildReceipt: null | components["schemas"]["BuildReceipt"];
            buildLog: null | string;
            entryType: null | string;
            sources: null | components["schemas"]["SourceFile"][];
        };
        BuildReceipt: {
            /** Format: uuid */
            botVersionId: string;
            sourceSha256: string;
            artifactSha256: string;
            /** Format: int64 */
            artifactSizeBytes: number;
            sdkVersion: string;
            guestAdapterVersion: string;
            ilcLlvmVersion: string;
            buildPipelineVersion: string;
            gameRulesVersion: string;
            runtimeProtocolVersion: string;
            runtimeConfigurationVersion: string;
            compilerImageReference: string;
            gitCommit: string;
            /** Format: date-time */
            builtAt: string;
        };
        ChallengeRequest: {
            /** Format: uuid */
            botId: string;
            /** Format: uuid */
            opponentBotId: string;
            mapId: null | string;
            /** Format: int64 */
            seed: null | number;
        };
        CosmeticCatalogEntry: {
            key: string;
            kind: string;
            id: string;
            label: string;
            availability: string;
            unlock: null | components["schemas"]["CosmeticUnlock"];
            owned: boolean;
            progress?: null | components["schemas"]["CosmeticProgress"];
        };
        CosmeticCatalogResponse: {
            /** Format: int32 */
            version: number;
            items: components["schemas"]["CosmeticCatalogEntry"][];
        };
        CosmeticProgress: {
            /** Format: int32 */
            current: number;
            /** Format: int32 */
            target: number;
            unit: string;
        };
        CosmeticUnlock: {
            sourceKind: string;
            sourceId: string;
            hint: string;
        };
        CreateBotRequest: {
            name: string;
            accent: null | string;
            lookId?: null | string;
            projectileLookId?: null | string;
        };
        CreatedBot: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            accent: string;
            lookId: string;
            projectileLookId: string;
        };
        CreatedMatchResponse: {
            /** Format: uuid */
            id: string;
        };
        CreatedMatchSetResponse: {
            /** Format: uuid */
            id: string;
        };
        EntitlementEarnedPayload: {
            sourceKind: string;
            sourceId: string;
            reason: null | string;
            items: components["schemas"]["EntitlementNotificationItem"][];
        };
        EntitlementNotificationItem: {
            key: string;
            kind: string;
            id: string;
            label: string;
        };
        LadderStanding: {
            /** Format: uuid */
            botId: string;
            rulesVersion: string;
            /** Format: double */
            rating: number;
            /** Format: int32 */
            rankedSets: number;
            /** Format: int32 */
            rank: number;
        };
        LeaderboardEntryResponse: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            accent: string;
            lookId: string;
            owner: string;
            /** Format: double */
            rating: number;
            /** Format: int32 */
            rankedSets: number;
            /** Format: int32 */
            rank: number;
        };
        LeaderboardResponse: {
            rulesVersion: string;
            activeRulesVersion: string;
            ladders: string[];
            entries: components["schemas"]["LeaderboardEntryResponse"][];
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        MatchDetailParticipantResponse: {
            /** Format: int32 */
            slot: number;
            /** Format: uuid */
            botId: string;
            nameSnapshot: string;
            ownerDisplayNameSnapshot: string;
            accentSnapshot: string;
            lookIdSnapshot: string;
            projectileLookIdSnapshot: string;
            artifactHashSnapshot: string;
            outcome: null | string;
            /** Format: int32 */
            finalHealth: null | number;
            /** Format: int32 */
            damageDealt: null | number;
            /** Format: int32 */
            faults: null | number;
        };
        MatchDetailResponse: {
            /** Format: uuid */
            id: string;
            mapId: string;
            /** Format: int64 */
            seed: number;
            status: string;
            broadcasting: boolean;
            /** Format: uuid */
            matchSetId: null | string;
            /** Format: int32 */
            setGame: null | number;
            /** Format: int32 */
            winnerSlot: null | number;
            endReason: null | string;
            /** Format: int32 */
            endTick: null | number;
            replayHash: null | string;
            error: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt: null | string;
            participants: components["schemas"]["MatchDetailParticipantResponse"][];
        };
        MatchLiveResponse: {
            status: string;
            /** Format: uuid */
            matchSetId: null | string;
            /** Format: int32 */
            setGame: null | number;
            /** Format: int32 */
            presentationTicksPerSecond: number;
            /** Format: int32 */
            presentationTick: number;
            /** Format: int32 */
            totalTicks: null | number;
            broadcastComplete: boolean;
            /** Format: int32 */
            countdownMs: number;
        };
        MatchSetBotResponse: {
            /** Format: uuid */
            id: string;
            name: null | string;
            accent: null | string;
            lookId: null | string;
        };
        MatchSetGameResponse: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            game: null | number;
            mapId: string;
            status: string;
            broadcasting: boolean;
            /** Format: uuid */
            winnerBotId: null | string;
            draw: boolean;
            participants: components["schemas"]["MatchSetParticipantResponse"][];
        };
        MatchSetParticipantResponse: {
            /** Format: int32 */
            slot: number;
            /** Format: uuid */
            botId: string;
            nameSnapshot: string;
            ownerDisplayNameSnapshot: string;
            accentSnapshot: string;
            lookIdSnapshot: string;
            projectileLookIdSnapshot: string;
        };
        MatchSetResponse: {
            /** Format: uuid */
            id: string;
            status: string;
            rulesVersion: string;
            botA: components["schemas"]["MatchSetBotResponse"];
            botB: components["schemas"]["MatchSetBotResponse"];
            /** Format: date-time */
            createdAt: string;
            revealed: boolean;
            /** Format: double */
            scoreA: null | number;
            /** Format: double */
            scoreB: null | number;
            /** Format: double */
            ratingChangeA: null | number;
            /** Format: double */
            ratingChangeB: null | number;
            /** Format: uuid */
            winnerBotId: null | string;
            games: components["schemas"]["MatchSetGameResponse"][];
        };
        MatchSummaryParticipantResponse: {
            /** Format: int32 */
            slot: number;
            nameSnapshot: string;
            ownerDisplayNameSnapshot: string;
            accentSnapshot: string;
            lookIdSnapshot: string;
            projectileLookIdSnapshot: string;
            outcome: null | string;
            /** Format: int32 */
            finalHealth: null | number;
        };
        MatchSummaryResponse: {
            /** Format: uuid */
            id: string;
            mapId: string;
            status: string;
            broadcasting: boolean;
            /** Format: uuid */
            matchSetId: null | string;
            /** Format: int32 */
            setGame: null | number;
            /** Format: int32 */
            winnerSlot: null | number;
            endReason: null | string;
            /** Format: int32 */
            endTick: null | number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt: null | string;
            participants: components["schemas"]["MatchSummaryParticipantResponse"][];
        };
        MetaMapResponse: {
            id: string;
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
            themeId: null | string;
        };
        MetaResponse: {
            engineVersion: string;
            gameRulesVersion: string;
            runtimeProtocolVersion: string;
            sdkVersion: string;
            buildPipelineVersion: string;
            cliVersion: string;
            maps: components["schemas"]["MetaMapResponse"][];
        };
        MyBotResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            accent: string;
            lookId: string;
            projectileLookId: string;
            latestVersion: null | components["schemas"]["MyBotVersionResponse"];
        };
        MyBotVersionResponse: {
            /** Format: int32 */
            versionNumber: number;
            status: string;
            isActive: boolean;
        };
        RankedChallengeRequest: {
            /** Format: uuid */
            botId: string;
            /** Format: uuid */
            opponentBotId?: null | string;
            rules?: null | string;
        };
        RegisterRequest: {
            displayName: string;
            email: string;
            password: string;
        };
        SourceFile: {
            relativePath: string;
            content: string;
        };
        SourceFileDto: {
            name: string;
            content: string;
        };
        SubmitVersionRequest: {
            entryType: string;
            files: components["schemas"]["SourceFileDto"][];
            lookId?: null | string;
            projectileLookId?: null | string;
        };
        SubmittedBotVersion: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            versionNumber: number;
            status: string;
        };
        UpdateBotAppearanceRequest: {
            accent: string;
            lookId: string;
            projectileLookId: string;
        };
        UpdatedBotAppearance: {
            /** Format: uuid */
            id: string;
            accent: string;
            lookId: string;
            projectileLookId: string;
        };
        UserNotificationResponse: {
            /** Format: uuid */
            id: string;
            kind: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            readAt: null | string;
            payload: components["schemas"]["EntitlementEarnedPayload"];
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            displayName: string;
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
