/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/connect/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connect/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cosmetics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CosmeticCatalogResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arena": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArenaCapabilitiesResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/ranked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RankedChallengeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedMatchSetResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ApplicationProblemResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ApplicationProblemResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ApplicationProblemResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ApplicationProblemResponse"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ApplicationProblemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matchsets/{setId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    setId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchSetResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    rules?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaderboardResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthProvidersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/external/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    returnUrl?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/callback/login/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StoreResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetaResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llms.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llms-full.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BotSummaryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBotRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedBot"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BotDetailResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}/appearance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBotAppearanceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdatedBotAppearance"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}/class": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignBotClassRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssignedBotClass"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}/build-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BotBuildStatusResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}/versions/{versionId}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitVersionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmittedBotVersion"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BotMatchHistoryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/{botId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    botId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BotStatistics"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bots/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MyBotResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChallengeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedMatchResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ApplicationProblemResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ApplicationProblemResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ApplicationProblemResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ApplicationProblemResponse"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ApplicationProblemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    take: number;
                    bot?: string;
                    map?: string;
                    ranked?: boolean;
                    skip?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchSummaryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{matchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    matchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchDetailResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{matchId}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    matchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchLiveResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{matchId}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    matchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/labs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LabsCatalogResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/labs/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateLabsMatchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedMatchResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arc-relay/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArcRelayCatalogResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arc-relay/entrants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArcRelayEntrantCardResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arc-relay/sheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArcRelaySheetResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveArcRelaySheetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArcRelaySheetResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arc-relay/sheets/{sheetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sheetId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveArcRelaySheetRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArcRelaySheetResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arc-relay/minds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateArcRelayMindRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArcRelayMindResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arc-relay/minds/{entrantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entrantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArcRelayMindResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entrantId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviseArcRelayMindRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArcRelayMindResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arc-relay/entrants/{entrantId}/crest-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entrantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArcRelayCrestOptionsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arc-relay/entrants/{entrantId}/crest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entrantId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetArcRelayCrestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArcRelayCrestDescriptor"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arc-relay/entrants/{entrantId}/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entrantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArcRelayPreflightResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arc-relay/entrants/{entrantId}/ladder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entrantId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetArcRelayLadderOptInRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArcRelayEntrantCardResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arc-relay/ladder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArcRelayLadderResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arc-relay/scrimmages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateArcRelayScrimmageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedMatchResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/arc-relay/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateArcRelayMatchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedMatchResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    take?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserNotificationResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    notificationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterDeviceRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deviceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationPreferenceResponse"][];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateNotificationPreferenceRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApplicationProblemResponse: {
            type: string;
            title: string;
            /** Format: int32 */
            status: number;
            detail: string;
            code: string;
            traceId: string;
            /** Format: int32 */
            retryAfterSeconds: null | number;
        };
        ArcRelayCarrierPolicy: {
            /** Format: int32 */
            handoffHealthAtOrBelow: number;
            preferAssignedTheater: boolean;
            /** Format: int32 */
            routeFailureTicks: number;
        };
        ArcRelayCatalogResponse: {
            playlistKey: string;
            /** Format: uuid */
            playlistVersionId: string;
            mapId: string;
            mapRows: string[];
            /** Format: int32 */
            slotCount: number;
            /** Format: int32 */
            maximumCopiesPerClass: number;
            theaters: string[];
            roles: string[];
            gambitTriggers: string[];
            classes: components["schemas"]["ArcRelayClassResponse"][];
            newSheetTemplate: components["schemas"]["ArcRelaySheetDocument"];
        };
        ArcRelayClassResponse: {
            id: string;
            name: string;
            signatureName: string;
            fantasy: string;
            starter: boolean;
            unlocked: boolean;
        };
        ArcRelayCompositionDeclaration: {
            classIds: string[];
            adaptivePolicyId?: null | string;
            adaptiveClassIds?: null | string[];
        };
        ArcRelayCompositionSlotResponse: {
            /** Format: int32 */
            slot: number;
            classId: string;
            className: string;
            lookId: string;
        };
        ArcRelayCrestDescriptor: {
            key: string;
            /** Format: int32 */
            variant: number;
            shape: string;
            pattern: string;
            mark: string;
            primary: string;
            secondary: string;
            detail: string;
        };
        ArcRelayCrestOptionsResponse: {
            /** Format: uuid */
            entrantId: string;
            options: components["schemas"]["ArcRelayCrestDescriptor"][];
        };
        ArcRelayEntrantCardResponse: {
            /** Format: uuid */
            id: string;
            kind: string;
            name: string;
            ownerDisplayName: string;
            /** Format: int32 */
            revision: number;
            crest: components["schemas"]["ArcRelayCrestDescriptor"];
            composition: components["schemas"]["ArcRelayCompositionSlotResponse"][];
            /** Format: double */
            rating: number;
            /** Format: int32 */
            rankedMatches: number;
            ladderOptedIn: boolean;
            status: string;
            suspensionReason: null | string;
            /** Format: uuid */
            suspensionMatchId: null | string;
            artifactHash: null | string;
            contentHash: string;
            isOwner: boolean;
        };
        ArcRelayEscortPolicy: {
            /** Format: int32 */
            followDistance: number;
            focusEnemyCarrier: boolean;
        };
        ArcRelayInterceptionPolicy: {
            focusEnemyCarrier: boolean;
            looseCoreFallback: boolean;
        };
        ArcRelayLadderResponse: {
            /** Format: uuid */
            ladderId: string;
            name: string;
            pairingPolicy: string;
            /** Format: int32 */
            maximumOptedInPerAccount: number;
            /** Format: int32 */
            maximumMatchesPerEntrantPerDay: number;
            entrants: components["schemas"]["ArcRelayEntrantCardResponse"][];
        };
        ArcRelayMatchEntrantResponse: {
            /** Format: uuid */
            entrantId: null | string;
            entrantKind: null | string;
            /** Format: int32 */
            entrantRevision: null | number;
            crest: null | components["schemas"]["ArcRelayCrestDescriptor"];
            composition: string[];
        };
        ArcRelayMindResponse: {
            entrant: components["schemas"]["ArcRelayEntrantCardResponse"];
            entryType: string;
            files: components["schemas"]["SourceFileDto"][];
            composition: components["schemas"]["ArcRelayCompositionDeclaration"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            buildLog: null | string;
        };
        ArcRelayPreflightResponse: {
            /** Format: uuid */
            matchId: string;
            status: string;
        };
        ArcRelaySheetDocument: {
            /** Format: int32 */
            schemaVersion: number;
            mapId: string;
            slots: components["schemas"]["ArcRelaySheetSlot"][];
            zones: components["schemas"]["ArcRelaySheetZone"][];
            rallyLines: components["schemas"]["ArcRelaySheetRallyLine"][];
            policies: components["schemas"]["ArcRelaySheetPolicies"];
            gambits: components["schemas"]["ArcRelaySheetGambit"][];
        };
        ArcRelaySheetGambit: {
            id: string;
            trigger: string;
            /** Format: int32 */
            durationTicks: number;
            /** Format: int32 */
            cooldownTicks: number;
            scopeRoles: string[];
            roleOverride: string;
            rallyLineId: string;
        };
        ArcRelaySheetPoint: {
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
        };
        ArcRelaySheetPolicies: {
            carrier: components["schemas"]["ArcRelayCarrierPolicy"];
            escort: components["schemas"]["ArcRelayEscortPolicy"];
            interception: components["schemas"]["ArcRelayInterceptionPolicy"];
        };
        ArcRelaySheetRallyLine: {
            id: string;
            points: components["schemas"]["ArcRelaySheetPoint"][];
        };
        ArcRelaySheetResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: int32 */
            revision: number;
            contentHash: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            document: components["schemas"]["ArcRelaySheetDocument"];
            entrant: components["schemas"]["ArcRelayEntrantCardResponse"];
        };
        ArcRelaySheetSlot: {
            /** Format: int32 */
            unitId: number;
            classId: string;
            theater: string;
            role: string;
            /** Format: int32 */
            partnerUnitId: number;
            outboundPath: components["schemas"]["ArcRelaySheetPoint"][];
            returnPath: components["schemas"]["ArcRelaySheetPoint"][];
        };
        ArcRelaySheetZone: {
            id: string;
            /** Format: int32 */
            minX: number;
            /** Format: int32 */
            minY: number;
            /** Format: int32 */
            maxX: number;
            /** Format: int32 */
            maxY: number;
        };
        ArenaAllowanceResponse: {
            /** Format: int32 */
            used: number;
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            remaining: number;
            /** Format: int32 */
            rollingWindowHours: number;
            /** Format: date-time */
            nextDailySlotAt: null | string;
            canStart: boolean;
            refusalCode: null | string;
            /** Format: date-time */
            retryAt: null | string;
        };
        ArenaCapabilitiesResponse: {
            format: components["schemas"]["DuelArenaFormatResponse"];
            unrankedAllowance: components["schemas"]["ArenaAllowanceResponse"];
            rankedAllowance: components["schemas"]["RankedArenaAllowanceResponse"];
            bots: components["schemas"]["MatchPlayabilityResponse"][];
        };
        ArenaRankedFormatResponse: {
            /** Format: int32 */
            gamesPerSet: number;
            /** Format: int32 */
            mapSeedPairs: number;
            mirroredSlots: boolean;
            mapPool: string[];
            /** Format: int32 */
            matchmakingPoolSize: number;
        };
        ArenaUnrankedFormatResponse: {
            /** Format: int32 */
            gamesPerMatch: number;
            defaultMapId: string;
        };
        AssignBotClassRequest: {
            classId: null | string;
        };
        AssignedBotClass: {
            /** Format: uuid */
            id: string;
            classId: string;
        };
        AuthProvidersResponse: {
            google: boolean;
        };
        BotActiveVersionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            versionNumber: number;
            artifactHash: null | string;
            supportedContractProfiles: null | string[];
        };
        BotBuildStatusResponse: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            versionNumber: number;
            status: string;
            artifactHash: null | string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            builtAt: null | string;
        };
        BotCombatTotals: {
            /** Format: int32 */
            games: number;
            /** Format: int32 */
            damageDealt: number;
            /** Format: int32 */
            faults: number;
        };
        BotDetailResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            accent: string;
            lookId: string;
            projectileLookId: string;
            /** Format: date-time */
            createdAt: string;
            owner: string;
            isOwner: boolean;
            currentStanding: null | components["schemas"]["LadderStanding"];
            versions: components["schemas"]["BotVersionResponse"][];
            classId?: null | string;
        };
        BotLadderRatingResponse: {
            rulesVersion: string;
            /** Format: double */
            rating: number;
            /** Format: int32 */
            rankedSets: number;
        };
        BotMatchHistoryResponse: {
            /** Format: int32 */
            wins: number;
            /** Format: int32 */
            losses: number;
            /** Format: int32 */
            draws: number;
            matches: components["schemas"]["BotMatchHistoryRowResponse"][];
        };
        BotMatchHistoryRowResponse: {
            /** Format: uuid */
            id: string;
            mapId: string;
            status: string;
            broadcasting: boolean;
            /** Format: uuid */
            matchSetId: null | string;
            /** Format: int32 */
            setGame: null | number;
            /** Format: date-time */
            createdAt: string;
            outcome: null | string;
            opponent: null | components["schemas"]["BotMatchOpponentResponse"];
        };
        BotMatchOpponentResponse: {
            /** Format: uuid */
            botId: string;
            nameSnapshot: string;
            ownerDisplayNameSnapshot: string;
            accentSnapshot: string;
            lookIdSnapshot: string;
        };
        BotRecord: {
            /** Format: int32 */
            played: number;
            /** Format: int32 */
            wins: number;
            /** Format: int32 */
            losses: number;
            /** Format: int32 */
            draws: number;
        };
        BotStatistics: {
            overall: components["schemas"]["BotRecord"];
            ranked: components["schemas"]["BotRecord"];
            unranked: components["schemas"]["BotRecord"];
            combat: components["schemas"]["BotCombatTotals"];
        };
        BotSummaryResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            accent: string;
            lookId: string;
            projectileLookId: string;
            /** Format: date-time */
            createdAt: string;
            ratings: components["schemas"]["BotLadderRatingResponse"][];
            owner: string;
            activeVersion: null | components["schemas"]["BotActiveVersionResponse"];
            /** Format: int32 */
            versionCount: number;
            currentStanding?: null | components["schemas"]["LadderStanding"];
            classId?: null | string;
        };
        BotVersionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            versionNumber: number;
            status: string;
            artifactHash: null | string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            buildReceipt: null | components["schemas"]["BuildReceipt"];
            buildLog: null | string;
            entryType: null | string;
            sources: null | components["schemas"]["SourceFile"][];
            supportedContractProfiles: null | string[];
        };
        BuildReceipt: {
            /** Format: uuid */
            botVersionId: string;
            sourceSha256: string;
            artifactSha256: string;
            /** Format: int64 */
            artifactSizeBytes: number;
            sdkVersion: string;
            guestAdapterVersion: string;
            ilcLlvmVersion: string;
            buildPipelineVersion: string;
            gameRulesVersion: string;
            runtimeProtocolVersion: string;
            runtimeConfigurationVersion: string;
            compilerImageReference: string;
            gitCommit: string;
            /** Format: date-time */
            builtAt: string;
            supportedContractProfiles?: null | string[];
        };
        ChallengeRequest: {
            /** Format: uuid */
            botId: string;
            /** Format: uuid */
            opponentBotId: string;
            mapId?: null | string;
            /** Format: int64 */
            seed?: null | number;
        };
        CosmeticCatalogEntry: {
            key: string;
            kind: string;
            id: string;
            label: string;
            availability: string;
            unlock: null | components["schemas"]["CosmeticUnlock"];
            owned: boolean;
            progress?: null | components["schemas"]["CosmeticProgress"];
        };
        CosmeticCatalogResponse: {
            /** Format: int32 */
            version: number;
            items: components["schemas"]["CosmeticCatalogEntry"][];
        };
        CosmeticProgress: {
            /** Format: int32 */
            current: number;
            /** Format: int32 */
            target: number;
            unit: string;
        };
        CosmeticUnlock: {
            sourceKind: string;
            sourceId: string;
            hint: string;
        };
        CreateArcRelayMatchRequest: {
            /** Format: uuid */
            sheetId: string;
            /** Format: uuid */
            opponentSheetId: string;
            /** Format: int64 */
            seed: null | number;
        };
        CreateArcRelayMindRequest: {
            name: string;
            entryType: string;
            files: components["schemas"]["SourceFileDto"][];
            composition: components["schemas"]["ArcRelayCompositionDeclaration"];
            /**
             * Format: int32
             * @default 0
             */
            crestVariant: number;
        };
        CreateArcRelayScrimmageRequest: {
            /** Format: uuid */
            entrantId: string;
            /** Format: uuid */
            opponentEntrantId: string;
            /** Format: int64 */
            seed: null | number;
        };
        CreateBotRequest: {
            name: string;
            accent: null | string;
            lookId?: null | string;
            projectileLookId?: null | string;
            classId?: null | string;
        };
        CreateLabsMatchRequest: {
            /** Format: uuid */
            playlistVersionId: string;
            entrantBotIds: string[];
            /** Format: int64 */
            seed: null | number;
        };
        CreatedBot: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            accent: string;
            lookId: string;
            projectileLookId: string;
            classId: null | string;
        };
        CreatedMatchResponse: {
            /** Format: uuid */
            id: string;
        };
        CreatedMatchSetResponse: {
            /** Format: uuid */
            id: string;
        };
        DuelArenaFormatResponse: {
            rulesVersion: string;
            requiredContractProfileId: string;
            unranked: components["schemas"]["ArenaUnrankedFormatResponse"];
            ranked: components["schemas"]["ArenaRankedFormatResponse"];
        };
        EntitlementNotificationItem: {
            key: string;
            kind: string;
            id: string;
            label: string;
        };
        LabsCatalogResponse: {
            enabled: boolean;
            playlists: components["schemas"]["LabsPlaylistResponse"][];
        };
        LabsPlaylistResponse: {
            /** Format: uuid */
            playlistVersionId: string;
            key: string;
            displayName: string;
            /** Format: int32 */
            version: number;
            gameModeId: string;
            rulesetId: string;
            matchFormatId: string;
            /** Format: int32 */
            participantCount: number;
            /** Format: int32 */
            scoringTeamCount: number;
            /** Format: int32 */
            participantsPerTeam: number;
            requiredContractProfileId: string;
        };
        LadderStanding: {
            /** Format: uuid */
            botId: string;
            rulesVersion: string;
            /** Format: double */
            rating: number;
            /** Format: int32 */
            rankedSets: number;
            /** Format: int32 */
            rank: number;
        };
        LeaderboardEntryResponse: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            accent: string;
            lookId: string;
            owner: string;
            /** Format: double */
            rating: number;
            /** Format: int32 */
            rankedSets: number;
            /** Format: int32 */
            rank: number;
        };
        LeaderboardResponse: {
            rulesVersion: string;
            activeRulesVersion: string;
            ladders: string[];
            entries: components["schemas"]["LeaderboardEntryResponse"][];
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        MatchDetailParticipantResponse: {
            /** Format: int32 */
            slot: number;
            /** Format: int32 */
            teamId: null | number;
            /** Format: uuid */
            botId: string;
            nameSnapshot: string;
            ownerDisplayNameSnapshot: string;
            accentSnapshot: string;
            lookIdSnapshot: string;
            projectileLookIdSnapshot: string;
            artifactHashSnapshot: string;
            outcome: null | string;
            /** Format: int32 */
            finalHealth: null | number;
            /** Format: int32 */
            damageDealt: null | number;
            /** Format: int32 */
            faults: null | number;
            entrant?: null | components["schemas"]["ArcRelayMatchEntrantResponse"];
        };
        MatchDetailResponse: {
            /** Format: uuid */
            id: string;
            mapId: string;
            gameRulesVersion: string;
            /** Format: int64 */
            seed: number;
            status: string;
            broadcasting: boolean;
            /** Format: uuid */
            matchSetId: null | string;
            /** Format: int32 */
            setGame: null | number;
            /** Format: int32 */
            winnerSlot: null | number;
            endReason: null | string;
            /** Format: int32 */
            endTick: null | number;
            replayHash: null | string;
            /** Format: int32 */
            replayFormatVersion: null | number;
            error: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt: null | string;
            participants: components["schemas"]["MatchDetailParticipantResponse"][];
            teamResults: components["schemas"]["MatchTeamResultResponse"][];
            arcRelayLane?: null | string;
        };
        MatchLiveResponse: {
            status: string;
            /** Format: uuid */
            matchSetId: null | string;
            /** Format: int32 */
            setGame: null | number;
            /** Format: double */
            presentationTicksPerSecond: number;
            /** Format: int32 */
            presentationTick: number;
            /** Format: int32 */
            totalTicks: null | number;
            broadcastComplete: boolean;
            /** Format: int32 */
            countdownMs: number;
        };
        MatchPlayabilityResponse: {
            /** Format: uuid */
            botId: string;
            isOwned: boolean;
            playable: boolean;
            refusalCode: null | string;
            refusalDetail: null | string;
        };
        MatchSetBotResponse: {
            /** Format: uuid */
            id: string;
            name: null | string;
            accent: null | string;
            lookId: null | string;
        };
        MatchSetGameResponse: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            game: null | number;
            mapId: string;
            status: string;
            broadcasting: boolean;
            /** Format: uuid */
            winnerBotId: null | string;
            draw: boolean;
            participants: components["schemas"]["MatchSetParticipantResponse"][];
        };
        MatchSetParticipantResponse: {
            /** Format: int32 */
            slot: number;
            /** Format: uuid */
            botId: string;
            nameSnapshot: string;
            ownerDisplayNameSnapshot: string;
            accentSnapshot: string;
            lookIdSnapshot: string;
            projectileLookIdSnapshot: string;
        };
        MatchSetResponse: {
            /** Format: uuid */
            id: string;
            status: string;
            rulesVersion: string;
            botA: components["schemas"]["MatchSetBotResponse"];
            botB: components["schemas"]["MatchSetBotResponse"];
            /** Format: date-time */
            createdAt: string;
            revealed: boolean;
            /** Format: double */
            scoreA: null | number;
            /** Format: double */
            scoreB: null | number;
            /** Format: double */
            ratingChangeA: null | number;
            /** Format: double */
            ratingChangeB: null | number;
            /** Format: uuid */
            winnerBotId: null | string;
            games: components["schemas"]["MatchSetGameResponse"][];
        };
        MatchSummaryParticipantResponse: {
            /** Format: int32 */
            slot: number;
            nameSnapshot: string;
            ownerDisplayNameSnapshot: string;
            accentSnapshot: string;
            lookIdSnapshot: string;
            projectileLookIdSnapshot: string;
            outcome: null | string;
            /** Format: int32 */
            finalHealth: null | number;
        };
        MatchSummaryResponse: {
            /** Format: uuid */
            id: string;
            mapId: string;
            status: string;
            broadcasting: boolean;
            /** Format: uuid */
            matchSetId: null | string;
            /** Format: int32 */
            setGame: null | number;
            /** Format: int32 */
            winnerSlot: null | number;
            endReason: null | string;
            /** Format: int32 */
            endTick: null | number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt: null | string;
            participants: components["schemas"]["MatchSummaryParticipantResponse"][];
        };
        MatchTeamResultResponse: {
            /** Format: int32 */
            teamId: number;
            /** Format: int32 */
            placement: number;
            outcome: string;
            scores: components["schemas"]["MatchTeamScoreResponse"][];
        };
        MatchTeamScoreResponse: {
            scoreChannelId: string;
            value: string;
        };
        MetaBotClassResponse: {
            id: string;
        };
        MetaMapResponse: {
            id: string;
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
            themeId: null | string;
        };
        MetaResponse: {
            engineVersion: string;
            gameRulesVersion: string;
            runtimeProtocolVersion: string;
            sdkVersion: string;
            buildPipelineVersion: string;
            cliVersion: string;
            maps: components["schemas"]["MetaMapResponse"][];
            botClasses: components["schemas"]["MetaBotClassResponse"][];
        };
        MyBotResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            accent: string;
            lookId: string;
            projectileLookId: string;
            latestVersion: null | components["schemas"]["MyBotVersionResponse"];
            classId?: null | string;
        };
        MyBotVersionResponse: {
            /** Format: int32 */
            versionNumber: number;
            status: string;
            isActive: boolean;
        };
        NotificationPreferenceResponse: {
            kind: string;
            pushEnabled: boolean;
        };
        RankedArenaAllowanceResponse: {
            /** Format: int32 */
            used: number;
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            remaining: number;
            /** Format: int32 */
            rollingWindowHours: number;
            /** Format: date-time */
            nextDailySlotAt: null | string;
            /** Format: int32 */
            inProgress: number;
            /** Format: int32 */
            concurrencyLimit: number;
            canStart: boolean;
            refusalCode: null | string;
            /** Format: date-time */
            retryAt: null | string;
        };
        RankedChallengeRequest: {
            /** Format: uuid */
            botId: string;
            /** Format: uuid */
            opponentBotId?: null | string;
            rules?: null | string;
        };
        RegisterDeviceRequest: {
            pushToken: string;
            deviceId: string;
            platform: string;
        };
        RegisterRequest: {
            displayName: string;
            email: string;
            password: string;
        };
        ReviseArcRelayMindRequest: {
            name: string;
            /** Format: int32 */
            expectedRevision: number;
            entryType: string;
            files: components["schemas"]["SourceFileDto"][];
            composition: components["schemas"]["ArcRelayCompositionDeclaration"];
        };
        SaveArcRelaySheetRequest: {
            name: string;
            /** Format: int32 */
            expectedRevision: null | number;
            document: components["schemas"]["ArcRelaySheetDocument"];
        };
        SetArcRelayCrestRequest: {
            /** Format: int32 */
            variant: number;
        };
        SetArcRelayLadderOptInRequest: {
            optedIn: boolean;
        };
        SourceFile: {
            relativePath: string;
            content: string;
        };
        SourceFileDto: {
            name: string;
            content: string;
        };
        StoreCategoryResponse: {
            id: string;
            label: string;
            packs: components["schemas"]["StorePackResponse"][];
        };
        StorePackItemResponse: {
            key: string;
            kind: string;
            id: string;
            label: string;
        };
        StorePackResponse: {
            id: string;
            label: string;
            description: string;
            items: components["schemas"]["StorePackItemResponse"][];
            owned: boolean;
            repeatable: boolean;
        };
        StoreResponse: {
            open: boolean;
            categories: components["schemas"]["StoreCategoryResponse"][];
        };
        SubmitVersionRequest: {
            entryType: string;
            files: components["schemas"]["SourceFileDto"][];
            lookId?: null | string;
            projectileLookId?: null | string;
        };
        SubmittedBotVersion: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            versionNumber: number;
            status: string;
        };
        UpdateBotAppearanceRequest: {
            accent: string;
            lookId: string;
            projectileLookId: string;
        };
        UpdateNotificationPreferenceRequest: {
            kind: string;
            pushEnabled: boolean;
        };
        UpdatedBotAppearance: {
            /** Format: uuid */
            id: string;
            accent: string;
            lookId: string;
            projectileLookId: string;
        };
        UserNotificationPayload: components["schemas"]["UserNotificationPayloadEntitlementEarnedPayload"] | components["schemas"]["UserNotificationPayloadMatchChallengedPayload"] | components["schemas"]["UserNotificationPayloadMatchSettledPayload"] | components["schemas"]["UserNotificationPayloadSetSettledPayload"];
        UserNotificationPayloadEntitlementEarnedPayload: {
            /** @enum {string} */
            kind: "entitlement-earned";
            sourceKind: string;
            sourceId: string;
            reason: null | string;
            items: components["schemas"]["EntitlementNotificationItem"][];
        };
        UserNotificationPayloadMatchChallengedPayload: {
            /** @enum {string} */
            kind: "match-challenged";
            /** Format: uuid */
            matchId: string;
            mapId: string;
            /** Format: uuid */
            botId: string;
            botName: string;
            botLookId: string;
            botAccent: string;
            challengerName: string;
        };
        UserNotificationPayloadMatchSettledPayload: {
            /** @enum {string} */
            kind: "match-settled";
            /** Format: uuid */
            matchId: string;
            mapId: string;
            /** Format: uuid */
            botId: string;
            botName: string;
            botLookId: string;
            botAccent: string;
            outcome: string;
            opponentName: string;
        };
        UserNotificationPayloadSetSettledPayload: {
            /** @enum {string} */
            kind: "set-settled";
            /** Format: uuid */
            matchSetId: string;
            /** Format: uuid */
            botId: string;
            botName: string;
            botLookId: string;
            botAccent: string;
            outcome: string;
            /** Format: double */
            score: number;
            /** Format: double */
            opponentScore: number;
            /** Format: double */
            ratingChange: number;
            opponentName: string;
        };
        UserNotificationResponse: {
            /** Format: uuid */
            id: string;
            kind: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            readAt: null | string;
            payload: components["schemas"]["UserNotificationPayload"];
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            displayName: string;
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
