// <auto-generated />
using System;
using BotArena.App.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BotArena.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722160751_RatingDefault")]
    partial class RatingDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BotArena.App.Accounts.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BotArena.App.Bots.Bot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accent")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RankedSets")
                        .HasColumnType("integer");

                    b.Property<double>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1200.0);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Bots");
                });

            modelBuilder.Entity("BotArena.App.Bots.BotVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactHash")
                        .HasColumnType("text");

                    b.Property<string>("ArtifactPath")
                        .HasColumnType("text");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuildLog")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BuiltAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameRulesVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestBotName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RuntimeConfigurationVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuntimeProtocolVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourcesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BotId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("BotVersions");
                });

            modelBuilder.Entity("BotArena.App.Jobs.BackgroundJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status", "AvailableAt");

                    b.ToTable("BackgroundJobs");
                });

            modelBuilder.Entity("BotArena.App.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BroadcastStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndReason")
                        .HasColumnType("text");

                    b.Property<int?>("EndTick")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("GameRulesVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MapVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MatchSetId")
                        .HasColumnType("uuid");

                    b.Property<int>("PresentationTicksPerSecond")
                        .HasColumnType("integer");

                    b.Property<string>("ReplayHash")
                        .HasColumnType("text");

                    b.Property<string>("ReplayPath")
                        .HasColumnType("text");

                    b.Property<string>("RuntimeConfigurationVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint");

                    b.Property<int?>("SetGame")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("WinnerSlot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MatchSetId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("BotArena.App.Matches.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccentSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArtifactHashSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotVersionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DamageDealt")
                        .HasColumnType("integer");

                    b.Property<int?>("Faults")
                        .HasColumnType("integer");

                    b.Property<int?>("FinalHealth")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "Slot")
                        .IsUnique();

                    b.ToTable("MatchParticipants");
                });

            modelBuilder.Entity("BotArena.App.Matches.MatchSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotAVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotBId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotBVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameRulesVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RatingABefore")
                        .HasColumnType("double precision");

                    b.Property<double>("RatingBBefore")
                        .HasColumnType("double precision");

                    b.Property<double>("RatingChangeA")
                        .HasColumnType("double precision");

                    b.Property<double>("RatingChangeB")
                        .HasColumnType("double precision");

                    b.Property<string>("RuntimeConfigurationVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ScoreA")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreB")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("WinnerBotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("MatchSets");
                });

            modelBuilder.Entity("BotArena.App.Bots.Bot", b =>
                {
                    b.HasOne("BotArena.App.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotArena.App.Bots.BotVersion", b =>
                {
                    b.HasOne("BotArena.App.Bots.Bot", null)
                        .WithMany("Versions")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotArena.App.Matches.MatchParticipant", b =>
                {
                    b.HasOne("BotArena.App.Matches.Match", null)
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BotArena.App.Bots.Bot", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("BotArena.App.Matches.Match", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
