// <auto-generated />
// Source sheet SHA-256: 2ff8364970ce7ec7e57a25f813bbe52b9fe9723e4bfbf98cca6a0044a1e3ab09
using BotArena.Sdk;

internal static class StockSheet
{
    internal const string Schema = "arc-relay-evaluation-sheet-v0";
    internal const string SheetId = "stock-balanced-gambit-v0";
    internal const string MapId = "arc-relay-threefold-01";
    internal const string SourceSha256 = "2ff8364970ce7ec7e57a25f813bbe52b9fe9723e4bfbf98cca6a0044a1e3ab09";

    internal static readonly string[] Composition = ["kestrel", "towline", "relay", "palisade", "switchback", "hush", "lantern", "patchbay"];

    internal static readonly UnitPlan[] Units =
    [
        new(0, "north", "carrier", 1, [new(4, 8), new(8, 7), new(12, 6), new(15, 4)], [new(12, 6), new(8, 8), new(5, 10), new(2, 11)]),
        new(1, "north", "screen", 0, [new(4, 9), new(8, 8), new(12, 7), new(14, 5)], [new(11, 7), new(7, 9), new(4, 10), new(2, 12)]),
        new(2, "centre", "carrier", 3, [new(5, 10), new(8, 9), new(12, 9), new(15, 11)], [new(12, 13), new(8, 13), new(5, 12), new(2, 11)]),
        new(3, "centre", "screen", 2, [new(4, 11), new(8, 11), new(12, 11), new(14, 11)], [new(11, 11), new(7, 11), new(4, 11), new(2, 10)]),
        new(4, "south", "carrier", 5, [new(4, 13), new(8, 15), new(12, 16), new(15, 18)], [new(12, 16), new(8, 14), new(5, 12), new(2, 11)]),
        new(5, "south", "intercept", 4, [new(5, 14), new(9, 15), new(13, 16), new(15, 18)], [new(12, 15), new(8, 13), new(4, 12), new(2, 12)]),
        new(6, "centre", "intercept", 2, [new(5, 13), new(8, 12), new(11, 12), new(14, 12)], [new(10, 12), new(6, 12), new(3, 12), new(2, 11)]),
        new(7, "centre", "reserve", 3, [new(5, 14), new(8, 13), new(11, 13), new(13, 12)], [new(9, 13), new(6, 13), new(3, 12), new(2, 11)]),
    ];

    internal static readonly Dictionary<string, Zone> Zones =
        new(StringComparer.Ordinal)
    {
        ["centre"] = new(10, 7, 20, 15),
        ["intercept"] = new(9, 2, 21, 20),
        ["north"] = new(11, 1, 19, 8),
        ["south"] = new(11, 14, 19, 21),
    };

    internal static readonly Dictionary<string, Position[]> RallyLines =
        new(StringComparer.Ordinal)
    {
        ["forward"] = [new(13, 6), new(13, 9), new(13, 12), new(13, 16)],
        ["home"] = [new(5, 8), new(5, 10), new(5, 12), new(5, 14)],
        ["middle"] = [new(9, 7), new(9, 10), new(9, 13), new(9, 16)],
    };

    internal static readonly CarrierPolicy Carrier = new(
        2,
        true,
        12);
    internal static readonly EscortPolicy Escort = new(
        1,
        true);
    internal static readonly InterceptionPolicy Interception = new(
        true,
        true);

    internal static readonly GambitPlan[] Gambits =
    [
        new(10, "pulse-backstop", "after-enemy-pulse", 75, "intercept", "home"),
        new(20, "two-core-collapse", "double-enemy-possession", 45, "intercept", "middle"),
        new(30, "pulse-release", "after-own-pulse", 55, "carrier", "forward"),
        new(40, "wipe-rally", "wipe", 60, "reserve", "home"),
        new(50, "route-release", "route-failure", 35, "carrier", "forward"),
    ];
}
