<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>botarena</AssemblyName>
    <RootNamespace>BotArena.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BotArena.Engine/BotArena.Engine.csproj" />
    <ProjectReference Include="../BotArena.Runtime/BotArena.Runtime.csproj" />
  </ItemGroup>
</Project>
