import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { decodeReplay, ReplayDecodeError } from '../src/replayNormalize.ts';

/**
 * THE MIND MIRROR (docs/DESIGN-MIND-ARCHITECTURE-2026-07-31.md §5.3). The
 * division of labour is the one `replayV3Normalize.ts` already states for the
 * #185 team seed: *the viewer refuses only what it can decide alone*. The
 * mirror bounds-checks and re-derives what one document contains; the C#
 * validator re-derives against the engine.
 *
 * The fixture is an engine-authored broadcast prefix of a real mind match,
 * regenerated by `GenericMindReplayV3Tests` under `UPDATE_GOLDEN=1`, so a
 * shape change in the writer fails here rather than in production.
 */
function mindDocument(): unknown {
  return JSON.parse(
    readFileSync(
      new URL('./fixtures/generic-mind-replay-v3.json', import.meta.url),
      'utf8',
    ),
  ) as unknown;
}

function forge(mutate: (root: Record<string, any>) => void): unknown {
  const root = mindDocument() as Record<string, any>;
  mutate(root);
  return root;
}

function refused(
  mutate: (root: Record<string, any>) => void,
  pattern: RegExp,
): void {
  assert.throws(() => decodeReplay(forge(mutate)), ReplayDecodeError);
  assert.throws(() => decodeReplay(forge(mutate)), pattern);
}

test('a real mind document decodes, and the union is carried once', () => {
  const decoded = decodeReplay(mindDocument());
  assert.equal(decoded.replayVersion, 3);
  const model = decoded.replay;
  assert.equal(
    model.versions.actorRuntime?.family,
    'generic-mind-match-1',
  );

  // The document stores ONE observation per participant per tick — the union
  // is not repeated per body — and the model still exposes one turn per body,
  // because the specialization is what keeps the whole viewer profile-blind.
  const raw = mindDocument() as {
    header: { runtime: { contractProfileId: string } };
    ticks: {
      mindTurns: {
        resolutions: unknown[];
        observation: { bodies: unknown[]; visibleTiles: unknown[] };
      }[];
    }[];
  };
  assert.equal(
    raw.header.runtime.contractProfileId,
    'generic-mind-match-1',
  );
  const tick = model.ticks[4];
  assert.equal(raw.ticks[4].mindTurns.length, 2);
  for (const turn of raw.ticks[4].mindTurns) {
    assert.equal(turn.resolutions.length, turn.observation.bodies.length);
    assert.ok(turn.observation.visibleTiles.length > 0);
  }
  assert.equal(tick.actorTurns.length, tick.activeActorKeys.length);
  for (const turn of tick.actorTurns) {
    assert.equal(turn.observation.completeness, 'exact');
    assert.ok(turn.observation.visibleTiles.length > 0);
    assert.equal(turn.observation.self?.actor.identity.actorKey, turn.actorKey);
  }

  // And the mind's own words ride through to presentation. (Nobody has seen an
  // enemy yet this early in the prefix; the enemy half of §12.2 is pinned on a
  // full match by the engine suite, where a body is actually in vision.)
  assert.ok(
    tick.actorTurns.every(
      (turn) => turn.observation.self?.roleTag === 'channeler',
    ),
  );
});

test('the turn kind is decided by the profile, never by the payload', () => {
  refused((root) => {
    root.ticks[4].actorTurns = [];
  }, /actorTurns: unknown property/);
  refused((root) => {
    delete root.ticks[4].mindTurns;
  }, /mindTurns: missing required property/);
});

test('a forged fuel budget is refused', () => {
  refused(
    (root) => {
      root.ticks[4].mindTurns[0].fuelBudget = '1800000000';
    },
    /must be exactly 250M \+ 200M per live body/,
  );
});

test('a resolution set that is not the own live bodies is refused', () => {
  refused(
    (root) => {
      root.ticks[4].mindTurns[0].resolutions.pop();
    },
    /must cover exactly the live body count/,
  );
});

test('a decision claimed accepted on a body that is not live is refused', () => {
  refused(
    (root) => {
      root.ticks[4].mindTurns[0].commands[0].unitId = 97;
    },
    /accepted a command on a body that is not an own live body/,
  );
});

test('two commands for one body are refused on a healthy turn', () => {
  refused(
    (root) => {
      const commands = root.ticks[4].mindTurns[0].commands;
      commands.push(structuredClone(commands[0]));
    },
    /cannot command the same body twice/,
  );
});

test('a role tag over the cap or off the charset is refused', () => {
  refused(
    (root) => {
      root.ticks[4].mindTurns[0].commands[0].roleTag = 'a'.repeat(25);
    },
    /must not exceed 24 UTF-8 bytes/,
  );
  refused(
    (root) => {
      root.ticks[4].mindTurns[0].commands[0].roleTag = 'Channeler';
    },
    /roleTag/,
  );
});

test('a published role tag the mind never set is refused', () => {
  refused(
    (root) => {
      root.ticks[4].mindTurns[0].observation.bodies[0].roleTag = 'sacrifice';
    },
    /publishes a role tag its mind never set on that body/,
  );
});

test('a forged body random seed is refused', () => {
  refused(
    (root) => {
      root.ticks[4].mindTurns[0].observation.bodies[0].bodyRandomSeed = '1';
    },
    /body random seed must be the seed declared at that life start/,
  );
});

test('a reserved chassis selection and a non-empty allied intent are refused', () => {
  refused(
    (root) => {
      root.ticks[4].mindTurns[0].observation.slots[0].selectedClassId =
        'striker';
    },
    /reserved chassis selection is never written by v1/,
  );
  refused(
    (root) => {
      root.ticks[4].mindTurns[0].observation.alliedIntents = [
        { participantId: 1, tagId: 'push', value: '1' },
      ];
    },
    /allied intents are reserved and always empty/,
  );
});

test('a slot table that is not the participant own slots is refused', () => {
  refused(
    (root) => {
      root.ticks[4].mindTurns[0].observation.slots.pop();
    },
    /must be exactly the participant own slots/,
  );
});

test('a body that disagrees with the frozen pre-state is refused', () => {
  refused(
    (root) => {
      root.ticks[4].mindTurns[0].observation.bodies[0].health = 99;
    },
    /must equal the exact frozen tick-start life/,
  );
});

test('a per-slot chassis is admitted on the topology, and only canonically', () => {
  // The deferred P1 mirror item (§9.2): `classId` on a unit slot is additive
  // under the #156 canonical discipline — written only when a ruleset declares
  // compositions, and refused as a second encoding of absence when explicitly
  // null. No shipped ruleset declares one yet (P7 mints the first), so the
  // mirror is exercised here rather than by a fixture.
  const withComposition = forge((root) => {
    for (const slot of root.header.contract.topology.unitSlots) {
      slot.classId = 'striker';
    }
  });
  assert.doesNotThrow(() => decodeReplay(withComposition));

  refused((root) => {
    root.header.contract.topology.unitSlots[0].classId = null;
  }, /classId/);
  refused((root) => {
    root.header.contract.topology.unitSlots[0].classId = 'Striker';
  }, /classId/);
});
